### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg_overlay'

### ISSUE THREAD

**Issue by LockFaiz** [zhouchenlin2096/Spikingformer#2]
Unexpected 'pretrained_cfg_overlay' error occurs 
<img width="560" alt="image" src="https://github.com/zhouchenlin2096/Spikingformer/assets/70676003/4f670840-6f51-4bce-8c25-36862703c427">
when I test model.py with timm 0.9.3.dev0,
This error seems fixed if I add "pretrained_cfg_overlay=None" in the "\_\_init__" of class "vit_snn" in model.py

**Comment by zhouchenlin2096** [comment]
Try ”timm==0.6.12“
