### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ShaopengLu** [zhouchenlin2096/Spikingformer#4]
INFO:train:Training with a single process on 1 GPUs.
Training with a single process on 1 GPUs.
Creating model
number of params: 29705768
INFO:train:Model vitsnn created, param count:29705768
Model vitsnn created, param count:29705768
INFO:timm.data.config:Data processing configuration for current model + dataset:
Data processing configuration for current model + dataset:
INFO:timm.data.config:	input_size: (3, 224, 224)
	input_size: (3, 224, 224)
INFO:timm.data.config:	interpolation: bicubic
	interpolation: bicubic
INFO:timm.data.config:	mean: (0.485, 0.456, 0.406)
	mean: (0.485, 0.456, 0.406)
INFO:timm.data.config:	std: (0.229, 0.224, 0.225)
	std: (0.229, 0.224, 0.225)
INFO:timm.data.config:	crop_pct: 1.0
	crop_pct: 1.0
INFO:train:Using native Torch AMP. Training in mixed precision.
Using native Torch AMP. Training in mixed precision.
ERROR:timm.models.helpers:No checkpoint found at '/media/data/spike-transformer-network/spikingformer_github/imagenet/output/train/Spikingformer_models/checkpoint-284.pth.tar'
ERROR: No checkpoint found at '/media/data/spike-transformer-network/spikingformer_github/imagenet/output/train/Spikingformer_models/checkpoint-284.pth.tar'
Traceback (most recent call last):
  File "D:\code\Spikingformer-master\imagenet\test.py", line 639, in <module>
    main()
  File "D:\code\Spikingformer-master\imagenet\test.py", line 437, in main
    resume_epoch = resume_checkpoint(
  File "D:\anaconda\envs\g1\lib\site-packages\timm\models\helpers.py", line 113, in resume_checkpoint
    raise FileNotFoundError()
FileNotFoundError
请问这个我该怎么解决？

**Comment by zhouchenlin2096** [comment]
Please check your env：timm==0.6.12; cupy==11.4.0; torch==1.12.1; spikingjelly==0.0.0.0.12; pyyaml;
